import json

import requests

from src.config import (
    OLLAMA_URL,
    AMALIA_MODEL,
    OLLAMA_TIMEOUT,
    TEMPERATURE,
)


SYSTEM_PROMPT = """
És o CLARA, um assistente especializado na consulta de legislação,
códigos e regulamentos portugueses.

Responde exclusivamente com base no contexto fornecido.

Regras:

1. Não utilizes conhecimento externo para completar informação em falta.
2. Não inventes artigos, números, taxas, datas, conceitos ou exceções.
3. Se o contexto não contiver informação suficiente para responder,
   indica claramente:
   "Não foi encontrada informação suficiente no contexto recuperado
   para responder com segurança."
4. Responde em português de Portugal.
5. Sempre que o contexto identifique o diploma, artigo ou número relevante,
   deves mencioná-los explicitamente na resposta.
6. Fundamenta a resposta nas disposições legais presentes no contexto,
   indicando a respetiva referência legal.
7. Quando existirem várias disposições relevantes, distingue-as claramente.
8. Mantém a resposta objetiva e juridicamente prudente.
9. Não apresentes a resposta como aconselhamento jurídico profissional.

Formato preferencial da resposta:

[Resposta objetiva]

Fundamento legal: [Diploma], artigo [artigo], n.º [número], quando esta
informação estiver disponível no contexto.
""".strip()


def check_llm_service() -> bool:
    """
    Check whether Ollama is reachable and the configured
    AMALIA model is available.

    Returns
    -------
    bool
        True if Ollama is reachable and the configured
        AMALIA model is installed. False otherwise.
    """

    try:
        # Retrieve the models currently available in Ollama.
        response = requests.get(
            f"{OLLAMA_URL}/api/tags",
            timeout=10,
        )

        response.raise_for_status()

        models = response.json().get(
            "models",
            []
        )

        installed_models = [
            model.get("name", "")
            for model in models
        ]

        # Accept both the exact model name and tagged variants.
        return any(
            name == AMALIA_MODEL
            or name.startswith(
                f"{AMALIA_MODEL}:"
            )
            for name in installed_models
        )

    except requests.RequestException:
        return False


def build_user_prompt(
    question: str,
    context: str,
) -> str:
    """
    Build the grounded prompt sent to the language model.

    Parameters
    ----------
    question : str
        Original user question.

    context : str
        Legal context retrieved from Qdrant.

    Returns
    -------
    str
        Formatted prompt containing the user question
        and the retrieved legal context.

    Raises
    ------
    ValueError
        If the question is empty.
    """

    if not question or not question.strip():
        raise ValueError(
            "A pergunta não pode estar vazia."
        )

    # Explicitly inform the model when no relevant
    # retrieval context is available.
    if not context or not context.strip():
        context = (
            "Não foi recuperado contexto "
            "relevante."
        )

    return f"""
Pergunta:
{question.strip()}

Contexto recuperado:
{context.strip()}

Responde à pergunta utilizando exclusivamente
o contexto acima.
""".strip()


def generate_answer(
    question: str,
    context: str,
    model: str = AMALIA_MODEL,
    temperature: float = TEMPERATURE,
) -> str:
    """
    Generate a complete grounded answer using AMALIA through Ollama.

    Parameters
    ----------
    question : str
        User question.

    context : str
        Legal context retrieved by the RAG pipeline.

    model : str
        Ollama model used for generation.

    temperature : float
        Sampling temperature used during generation.

    Returns
    -------
    str
        Complete answer generated by the model.

    Raises
    ------
    RuntimeError
        If the model does not return any textual content.

    requests.HTTPError
        If the Ollama API request fails.
    """

    user_prompt = build_user_prompt(
        question=question,
        context=context,
    )

    # Request a complete, non-streaming response from Ollama.
    response = requests.post(
        f"{OLLAMA_URL}/api/chat",
        json={
            "model": model,
            "stream": False,
            "messages": [
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                },
            ],
            "options": {
                "temperature": temperature,
            },
        },
        timeout=OLLAMA_TIMEOUT,
    )

    response.raise_for_status()

    data = response.json()

    message = data.get(
        "message",
        {}
    )

    content = message.get(
        "content"
    )

    if not content:
        raise RuntimeError(
            "O modelo não devolveu uma resposta."
        )

    return content.strip()


def stream_answer(
    question: str,
    context: str,
    model: str = AMALIA_MODEL,
    temperature: float = TEMPERATURE,
):
    """
    Stream a grounded AMALIA response through Ollama.

    Each text fragment is yielded as soon as it is generated
    by the model.

    Parameters
    ----------
    question : str
        User question.

    context : str
        Legal context retrieved by the RAG pipeline.

    model : str
        Ollama model used for generation.

    temperature : float
        Sampling temperature used during generation.

    Yields
    ------
    str
        Incremental fragments of the generated answer.

    Raises
    ------
    requests.HTTPError
        If the Ollama streaming request fails.
    """

    user_prompt = build_user_prompt(
        question=question,
        context=context,
    )

    # Keep the HTTP connection open so that Ollama can
    # return generation fragments progressively.
    with requests.post(
        f"{OLLAMA_URL}/api/chat",
        json={
            "model": model,
            "stream": True,
            "messages": [
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                },
            ],
            "options": {
                "temperature": temperature,
            },
        },
        stream=True,
        timeout=OLLAMA_TIMEOUT,
    ) as response:

        response.raise_for_status()

        for line in response.iter_lines():

            if not line:
                continue

            # Ollama returns one JSON object per line
            # while streaming the generated response.
            data = json.loads(
                line.decode("utf-8")
            )

            message = data.get(
                "message",
                {}
            )

            content = message.get(
                "content",
                ""
            )

            if content:
                yield content

            if data.get("done"):
                break